development:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: ember_try_development
  pool: 5
  username: 
  password: 

test:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: ember_try_test
  pool: 5
  username: 
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: ember_try_production
  pool: 5
  username:
  password: